// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/customer/customer.proto

package customer

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_api_customer_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_api_customer_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Customer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Customer) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Customer) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *Customer) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	BirthDate     string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_api_customer_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_customer_customer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateCustomerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateCustomerRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateCustomerRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

type CreateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_api_customer_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_customer_customer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCustomerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCustomerResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateCustomerResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateCustomerResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateCustomerResponse) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

var File_api_customer_customer_proto protoreflect.FileDescriptor

const file_api_customer_customer_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/customer/customer.proto\x12\x14customer.service.api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x9a\x02\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdb\x01\n" +
	"\x15CreateCustomerRequest\x127\n" +
	"\tuser_name\x18\x01 \x01(\tB\x1a\xfaB\x17r\x15\x10\x03\x1822\x0f^[a-zA-Z0-9_]+$R\buserName\x12$\n" +
	"\tfull_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18dR\bfullName\x12\x1b\n" +
	"\x04city\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18dR\x04city\x12F\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tB'\xfaB$r\"\x10\n" +
	"\x18\n" +
	"2\x1c^[0-9]{4}-[0-9]{2}-[0-9]{2}$R\tbirthDate\"\x95\x01\n" +
	"\x16CreateCustomerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate2\x9c\x01\n" +
	"\x0fCustomerService\x12\x88\x01\n" +
	"\x0eCreateCustomer\x12+.customer.service.api.CreateCustomerRequest\x1a,.customer.service.api.CreateCustomerResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/registerB5Z3github.com/erknas/customer-service/pkg/api/customerb\x06proto3"

var (
	file_api_customer_customer_proto_rawDescOnce sync.Once
	file_api_customer_customer_proto_rawDescData []byte
)

func file_api_customer_customer_proto_rawDescGZIP() []byte {
	file_api_customer_customer_proto_rawDescOnce.Do(func() {
		file_api_customer_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_customer_customer_proto_rawDesc), len(file_api_customer_customer_proto_rawDesc)))
	})
	return file_api_customer_customer_proto_rawDescData
}

var file_api_customer_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_customer_customer_proto_goTypes = []any{
	(*Customer)(nil),               // 0: customer.service.api.Customer
	(*CreateCustomerRequest)(nil),  // 1: customer.service.api.CreateCustomerRequest
	(*CreateCustomerResponse)(nil), // 2: customer.service.api.CreateCustomerResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_api_customer_customer_proto_depIdxs = []int32{
	3, // 0: customer.service.api.Customer.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: customer.service.api.Customer.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: customer.service.api.CustomerService.CreateCustomer:input_type -> customer.service.api.CreateCustomerRequest
	2, // 3: customer.service.api.CustomerService.CreateCustomer:output_type -> customer.service.api.CreateCustomerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_customer_customer_proto_init() }
func file_api_customer_customer_proto_init() {
	if File_api_customer_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_customer_customer_proto_rawDesc), len(file_api_customer_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_customer_customer_proto_goTypes,
		DependencyIndexes: file_api_customer_customer_proto_depIdxs,
		MessageInfos:      file_api_customer_customer_proto_msgTypes,
	}.Build()
	File_api_customer_customer_proto = out.File
	file_api_customer_customer_proto_goTypes = nil
	file_api_customer_customer_proto_depIdxs = nil
}
